import 'package:calendar_view/calendar_view.dart';
import 'package:flutter/material.dart';
 
class Course {
  final String title;
  final IconData icon;
  final int dayOfWeek;
  final int startHour;
  final int startMinute;
  final int endHour;
  final int endMinute;
  final String professor;
  final String aula;
  final Color color;
  final String professorOffice; 
  final String professorImage;
  final String nombreCompleto;

  Course({
    required this.title, 
    required this.icon, 
    required this.color,
    required this.dayOfWeek,
    required this.startHour,
    required this.startMinute,
    required this.endHour,
    required this.endMinute,
    required this.professor,
    required this.aula,
    required this.professorOffice,
    required this.professorImage, 
    required this.nombreCompleto,
    });
}

class CoursesProvider {
  static final CoursesProvider _instance = CoursesProvider._internal();

  factory CoursesProvider() {
    return _instance;
  }

  CoursesProvider._internal();

  final List<Course> courses = [
    Course(
      title: 'SO - Practicas 1',
      icon: Icons.computer,
      color: Colors.red,
      dayOfWeek: DateTime.monday,
      startHour: 8,
      startMinute: 30,
      endHour: 10,
      endMinute: 30,
      nombreCompleto: "Sistemas Operativos",
      professor: 'Alejandro Jose Leon Salas',
      aula: '2.3',
      professorOffice: 'Etsiit 3ª P Despacho 19',
      professorImage: 'assets/salas.png', //
    ),
    Course(
      title: 'SO - Teoría A',
      icon: Icons.code,
      color: Colors.redAccent,
      dayOfWeek: DateTime.monday,
      startHour: 10,
      startMinute: 30,
      endHour: 12,
      endMinute: 30,
      nombreCompleto: "Sistemas Operativos",
      professor: 'Alejandro Jose Leon Salas',
      aula: '1.2',
      professorOffice: 'Etsiit 3ª P Despacho 19',
      professorImage: 'assets/salas.png', 
    ),
    Course(
      title: 'EC - Teoria A',
      icon: Icons.computer,
      color: Color.fromARGB(255, 11, 120, 18),
      dayOfWeek: DateTime.monday,
      startHour: 12,
      startMinute: 30,
      endHour: 13,
      endMinute: 30,
      nombreCompleto: "Estructura de Computadores",
      professor: 'Ignacio Rojas Ruiz',
      aula: '3.6',
      professorOffice: 'Etsiit', 
      professorImage: 'assets/rojas.png', 
    ),
    Course(
      title: 'ED - Teoria A',
      icon: Icons.code,
      color: const Color.fromARGB(255, 219, 197, 36),
      dayOfWeek: DateTime.monday,
      startHour: 13,
      startMinute: 30,
      endHour: 14,
      endMinute: 30,
      nombreCompleto: "Estructura de Datos",
      professor: 'Joaquin Fernandez Valdivia',
      aula: '3.1',
      professorOffice: 'D12 Etsiit', 
      professorImage: 'assets/valdi.png', 
    ),
    Course(
      title: 'ED - Practicas 1',
      icon: Icons.storage,
      color: Color.fromARGB(255, 245, 227, 92),
      dayOfWeek: DateTime.tuesday,
      startHour: 8,
      startMinute: 30,
      endHour: 9,
      endMinute: 30,
      nombreCompleto: "Estructura de Datos",
      professor: 'Ignacio Aguilera Martos',
      aula: '0.2',
      professorOffice: 'Etsiit', 
      professorImage: 'assets/martos.png', 
    ),
    Course(
      title: 'EC - Prácticas 1',
      icon: Icons.storage,
      color: Color.fromARGB(255, 35, 177, 45),
      dayOfWeek: DateTime.tuesday,
      startHour: 9,
      startMinute: 30,
      endHour: 11,
      endMinute: 30,
      nombreCompleto: "Estructura de Computadores",
      professor: 'Ignacio Rojas Ruiz',
      aula: '2.5',
      professorOffice: 'Etsiit', 
      professorImage: 'assets/rojas.png', 
    ),
    Course(
      title: 'EC - Teoría A',
      icon: Icons.business,
      color: Color.fromARGB(255, 11, 120, 18),
      dayOfWeek: DateTime.tuesday,
      startHour: 11,
      startMinute: 30,
      endHour: 12,
      endMinute: 30,
      nombreCompleto: "Estructura de Computadores",
      professor: 'Ignacio Rojas Ruiz',
      aula: '0.1',
      professorOffice: 'Etsiit', 
      professorImage: 'assets/rojas.png', 
    ),
    Course(
      title: 'ED - Teoria A',
      icon: Icons.visibility,
      color: const Color.fromARGB(255, 219, 197, 36),
      dayOfWeek: DateTime.tuesday,
      startHour: 12,
      startMinute: 30,
      endHour: 14,
      endMinute: 30,
      nombreCompleto: "Estructura de Datos",
      professor: 'Joaquin Fernandez Valdivia',
      aula: '1.7',
      professorOffice: 'D12 Etsiit', 
      professorImage: 'assets/valdi.png', 
    ),
    Course(
      title: 'AM I - Teoria A',
      icon: Icons.business,
      color: Color.fromARGB(255, 68, 97, 241),
      dayOfWeek: DateTime.wednesday,
      startHour: 9,
      startMinute: 00,
      endHour: 10,
      endMinute: 00,
      nombreCompleto: "Analisis Matematico I",
      professor: 'Rafael Paya Albert',
      aula: '1.4',
      professorOffice: 'Facultad de Ciencias D5', 
      professorImage: 'assets/paya.png', 
    ),
    Course(
      title: 'AM I - Practicas 1',
      icon: Icons.business,
      color: Color.fromARGB(255, 68, 160, 241),
      dayOfWeek: DateTime.wednesday,
      startHour: 10,
      startMinute: 00,
      endHour: 11,
      endMinute: 00,
      nombreCompleto: "Analisis Matematico I",
      professor: 'Rafael Paya Albert',
      aula: '1.4',
      professorOffice: 'Facultad de Ciencias D5', 
      professorImage: 'assets/paya.png', 
    ),
    Course(
      title: 'GEO III - Teoria A',
      icon: Icons.business,
      color: const Color.fromARGB(255, 124, 52, 193),
      dayOfWeek: DateTime.wednesday,
      startHour: 11,
      startMinute: 00,
      endHour: 12,
      endMinute: 00,
      nombreCompleto: "Geometría III",
      professor: 'Antonio Martinez Lopez',
      aula: '1.4',
      professorOffice: 'Facultad de Ciencias', 
      professorImage: 'assets/npc.png', 
    ),

    Course(
      title: 'TOPO I - Teoria A',
      icon: Icons.business,
      color: Color.fromARGB(255, 249, 171, 3),
      dayOfWeek: DateTime.wednesday,
      startHour: 12,
      startMinute: 00,
      endHour: 13,
      endMinute: 00,
      nombreCompleto: "Topología I",
      professor: 'Antonio Martinez Lopez',
      aula: '1.4',
      professorOffice: 'Facultad de Ciencias', 
      professorImage: 'assets/npc.png', 
    ),
    Course(
      title: 'AM I - Teoria A',
      icon: Icons.business,
      color: Color.fromARGB(255, 68, 97, 241),
      dayOfWeek: DateTime.thursday,
      startHour: 9,
      startMinute: 00,
      endHour: 10,
      endMinute: 00,
      nombreCompleto: "Analisis Matematico I",
      professor: 'Rafael Paya Albert',
      aula: '1.4',
      professorOffice: 'Facultad de Ciencias D5', 
      professorImage: 'assets/paya.png', 
    ),
    Course(
      title: 'GEO III - Teoria A',
      icon: Icons.business,
      color: const Color.fromARGB(255, 124, 52, 193),
      dayOfWeek: DateTime.thursday,
      startHour: 10,
      startMinute: 00,
      endHour: 11,
      endMinute: 00,
      nombreCompleto: "Geometría III",
      professor: 'Antonio Martinez Lopez',
      aula: '1.4',
      professorOffice: 'Facultad de Ciencias', 
      professorImage: 'assets/npc.png', 
    ),
    Course(
      title: 'GEO III - Practicas 1',
      icon: Icons.business,
      color: Color.fromARGB(255, 148, 64, 226),
      dayOfWeek: DateTime.thursday,
      startHour: 11,
      startMinute: 00,
      endHour: 12,
      endMinute: 00,
      nombreCompleto: "Geometría III",
      professor: 'Antonio Martinez Lopez',
      aula: '1.4',
      professorOffice: 'Facultad de Ciencias', 
      professorImage: 'assets/npc.png', 
    ),

    Course(
      title: 'TOPO I - Teoria A',
      icon: Icons.business,
      color: Color.fromARGB(255, 249, 171, 3),
      dayOfWeek: DateTime.thursday,
      startHour: 12,
      startMinute: 00,
      endHour: 13,
      endMinute: 00,
      nombreCompleto: "Topología I",
      professor: 'Antonio Martinez Lopez',
      aula: '1.4',
      professorOffice: 'Facultad de Ciencias',
      professorImage: 'assets/npc.png', 
    ),

    Course(
      title: 'AM I - Teoria A',
      icon: Icons.business,
      color: Color.fromARGB(255, 68, 97, 241),
      dayOfWeek: DateTime.friday,
      startHour: 9,
      startMinute: 00,
      endHour: 10,
      endMinute: 00,
      professor: 'Rafael Paya Albert',
      nombreCompleto: "Analisis Matematico I",
      aula: '1.4',
      professorOffice: 'Facultad de Ciencias D5', 
      professorImage: 'assets/paya.png', 
    ),
    Course(
      title: 'GEO III - Teoria A',
      icon: Icons.business,
      color: const Color.fromARGB(255, 124, 52, 193),
      dayOfWeek: DateTime.friday,
      startHour: 10,
      startMinute: 00,
      endHour: 11,
      endMinute: 00,
      nombreCompleto: "Geometría III",
      professor: 'Antonio Martinez Lopez',
      aula: '1.4',
      professorOffice: 'Facultad de Ciencias', 
      professorImage: 'assets/npc.png', 
    ),
    Course(
     title: 'TOPO I - Teoria A',
      icon: Icons.business,
      color: Color.fromARGB(255, 249, 171, 3),
      dayOfWeek: DateTime.friday,
      startHour: 11,
      startMinute: 00,
      endHour: 12,
      endMinute: 00,
      nombreCompleto: "Topología I",
      professor: 'Antonio Martinez Lopez',
      aula: '1.4',
      professorOffice: 'Facultad de Ciencias', 
      professorImage: 'assets/npc.png', 
    ),

    Course(
      title: 'TOPO I - Practicas 1',
      icon: Icons.business,
      color: Color.fromARGB(255, 193, 148, 52),
      dayOfWeek: DateTime.friday,
      startHour: 12,
      startMinute: 00,
      endHour: 13,
      endMinute: 00,
      nombreCompleto: "Topología I",
      professor: 'Antonio Martinez Lopez',
      aula: '1.4',
      professorOffice: 'Facultad de Ciencias', 
      professorImage: 'assets/npc.png', 
    ),
  ];

  List<Course> getCourses() {
    return courses;
  }
}
